### ISSUE TITLE
Playthrough, Roadmap and Prototype Updates : Design It!

### ISSUE THREAD

**Issue by xacarob** [DigitalDenizen/FearAndLight#142]
Phase 2
===============

Definition of Done/Playthrough
- Opening Cinematic
- Title Screen with Play Buttons
-  One Hero, 1 Campfire, Spirit dog
-  Dog tells you village in bad way and tells you to fight scary monsters
-  Once you place down a hut and starts the mob spawner
-  Exploration, Item Gathering, Combat
- Once you find crystal you can then place it in pylon to trigger boss and get success or failure screen.

Requirements
- Fireball (Design and Code)
- Pylon/Beacon (Design and Code)
- Vampire Spider (Design and Code)
- Dire Wolf (Design and Code)
- Spirit Animal (Design and Code)
- Boss Trigger Attack (Design and Code)
- Fog of War (Design and Code)
- Start Menu (Design and Code)
- Health Bars (Design and Code)
- Dark Forest World (Transition/Tilesets)
- Failure and Success Screens (Design and Code)
- UI/Navigation
- Save Function
- Inventory System/Inventory Object Placement
- Item Drops
- Music

Roadmap Specific Tasks
===============
- [x] Game Roadmap in Miro

Scenes to be Added to Prototype
===============
- [x] Opening Cinematic
- [x] Title Screen with Play Buttons
- [x] One Hero, 1 Campfire, Spirit Lantern
- [x] Dog tells you village in bad way and tells you to fight scary monsters
- [x] Once you place down a hut and starts the mob spawner
- [x] Exploration, Item Gathering, Combat
- [x] Once you find crystal you can then place it in pylon to trigger boss and get success or failure screen.
